services:
  job-jays-api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: job-jays-api
    ports:
      - "8080:8080"
    # environment:
      # KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092  # Add this line

  applicant-job-matcher:
    build:
      context: ../applicant_job_matcher
      dockerfile: Dockerfile
    container_name: applicant-job-matcher
    depends_on:
      - job-jays-api
    # environment:
      # KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092  # Add this line

  preference-updater:
    build:
      context: ../preference_updater
      dockerfile: Dockerfile
    container_name: preference-updater
    depends_on:
      - job-jays-api
    # environment:
      # KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092  # Add this line

  notification-sender:
    build:
      context: ../notification_sender
      dockerfile: Dockerfile
    container_name: notification-sender
    depends_on:
      - job-jays-api
    # environment:
      # KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092  # Add this line
