name: Build and Test Backend Services

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Compose
      - name: Build Docker Compose Services
        run: |
          docker compose -f docker-compose.yml build

      # # Step 4: Start Services for Testing
      # - name: Start Docker Compose Services
      #   run: |
      #     docker compose -f docker-compose.yml up -d

      # # Step 5: Run Tests
      # - name: Run Tests in Docker Containers
      #   run: |
      #     docker exec job-jays-api ./gradlew test  # Example test command for Gradle-based service
      #     docker exec applicant-job-matcher ./gradlew test
      #     docker exec preference-updater ./gradlew test
      #     docker exec notification-sender ./gradlew test

      # Step 6: Tear Down Services
      - name: Tear Down Docker Compose Services
        if: always()
        run: |
          docker compose -f docker-compose.yml down --volumes
