name: Test SSH Connection and Create File

on:
  push:
    branches:
      - main  # Adjust to your target branch

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.JJ_SERVER_SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.JJ_SERVER_USERNAME }}
          SERVER_IP: ${{ secrets.HOST_JJ_SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Test Connection and Create File
        run: |
          ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP "echo 'This is a test file for SSH connection verification.' > ~/test_connection.txt"
